# Generated by Django 4.2.30 on 2026-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t_warranty',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
